-- IRIS Investing — Phase 5 · run the grader on a schedule
-- The grader is idempotent per (publication, horizon, grader_version), so a daily run only fills newly-due horizons.
-- 05:00 UTC is after the 04:15 UTC decisions refresh. (Applied to production 2026-09-15 via cron.schedule.)
--
-- select cron.schedule('market-grade-outcomes', '0 5 * * *', 'select market.grade_outcomes()');
--
-- Rollback: select cron.unschedule('market-grade-outcomes');
--
-- This file documents the schedule; on a fresh environment without pg_cron the grader is simply called manually or
-- from the app. The local stub's cron.schedule runs it immediately (see local_stubs.sql).
select 1;
